framework:
    workflows:
        payment:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            audit_trail:
                enabled: true
            supports:
                - App\Entity\Payment
            initial_marking: created
            places:
                - created
                - waiting_for_payment
                - payment_processing
                - waiting_for_payment_proposed
                - payment_completed
                - payout_completed
                - payment_declined
                - canceled
                - refunded
            transitions:
                confirm_payment:
                    from: created
                    to: waiting_for_payment
                propose_payment:
                    from: created
                    to: waiting_for_payment_proposed
                process_payment:
                    from: [waiting_for_payment,waiting_for_payment_proposed]
                    to: payment_processing
                complete_payment:
                    from: [waiting_for_payment, payment_declined, waiting_for_payment_proposed]
                    to: payment_completed
                payout:
                    from: payment_completed
                    to: payout_completed
                decline_payment:
                    from: [waiting_for_payment,waiting_for_payment_proposed]
                    to: payment_declined
                cancel_order:
                    from: [created, waiting_for_payment, payment_declined]
                    to: canceled
                refund_payment:
                    from: payment_completed
                    to: refunded
        